### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Shoma-Tatsumi** [shomaaan/furima-35056#14]

**Comment by Shoma-Tatsumi** [comment]
#URL
https://furima-35056.herokuapp.com/

#Basic認証とPassword
user
2525

#出品者情報
apple@apple.jp
apple1

#購入者情報
orange@orange.jp
orange1

**Comment by takumi0530** [comment]
@shomaaan さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/113542433-39a1f500-961f-11eb-94c7-9cf2b9055de0.png)
